pluginGroup = com.manvendrask.noctis
pluginId = com.manvendrask.noctis.jetbrains
pluginName = Noctis IDE Themes
pluginVersion = 1.0.0
pluginSinceBuild = 253
platformVersion = 2025.3

# Opt-out flag for bundling Kotlin standard library
kotlin.stdlib.default.dependency = false

org.gradle.configuration-cache = true
org.gradle.caching = true
org.gradle.parallel = true
